# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build .ipa"
  lane :beta do
    increment_build_number(xcodeproj: "Lasportago.xcodeproj")
    build_app(scheme: "Lasportago")

    firebase_app_distribution(
      app: "1:654924090917:ios:16b42981517ad2042479cc",
      groups: "tester",
      release_notes: "Test fastlane auto build to firebase"
    )
  end
end
